// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXGUoxjyJ-pMs1rmLFh9IJjOlF5dgmYlE',
    appId: '1:985692560713:web:483e0f6d10dd0049cf4e98',
    messagingSenderId: '985692560713',
    projectId: 'dam-u3-practica2-ambc',
    authDomain: 'dam-u3-practica2-ambc.firebaseapp.com',
    storageBucket: 'dam-u3-practica2-ambc.appspot.com',
    measurementId: 'G-K663MPJR9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXj8U-7sloL1YfSv8y7GtSGxwPxTyOOk4',
    appId: '1:985692560713:android:927d13fdd63b5167cf4e98',
    messagingSenderId: '985692560713',
    projectId: 'dam-u3-practica2-ambc',
    storageBucket: 'dam-u3-practica2-ambc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXEBRHZNBBPgjFrKHZyEPTGvrD0rdniuA',
    appId: '1:985692560713:ios:5b1bb5e6954b14a0cf4e98',
    messagingSenderId: '985692560713',
    projectId: 'dam-u3-practica2-ambc',
    storageBucket: 'dam-u3-practica2-ambc.appspot.com',
    iosBundleId: 'mx.edu.ittepic.damU3Practica2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXEBRHZNBBPgjFrKHZyEPTGvrD0rdniuA',
    appId: '1:985692560713:ios:584f9e3133821b10cf4e98',
    messagingSenderId: '985692560713',
    projectId: 'dam-u3-practica2-ambc',
    storageBucket: 'dam-u3-practica2-ambc.appspot.com',
    iosBundleId: 'mx.edu.ittepic.damU3Practica2.RunnerTests',
  );
}
